<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager   = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$paymentblock = $objectManager->get('Excellence\StoreCredit\Block\Payment');

if($customerSession->isLoggedIn()) {
$login = 1;
}
else{
$login = 0;
}
$quoteEntityId = $block->getQuoteId();
?>
<script>
var id= sessionStorage.getItem('AdminId');
console.log(id);
window.checkbox = id;

window.amount = "<?php echo $block->credit(); ?>";
window.login = "<?php echo $login ?>";
window.saveUrl= "<?php echo $storeManager->getStore()->getBaseUrl() . 'storecredit/checkout/totals'; ?>";
window.enable = "<?php echo $block->enable(); ?>";
window.quoteentityid = <?php echo $quoteEntityId; ?>;
window.zeroCheck = <?php echo $paymentblock->checkCredit(); ?>;
</script>
